
services:
  database:
    build: src/database/.
    container_name: database
    volumes:
      - sqlite-data:/app/data
  nginx:
    build: src/nginx/.
    container_name: nginx
    ports:
      - "1080:1080"
    networks:
      - webnet
    volumes:
      - sqlite-data:/app/data
    depends_on:
      - main_service
      - login_service
      - game_service
      - tournament_service
      - database
      - friends_service
      - profile_service
  main_service:
    build: src/main_service/service/.
    container_name: main_service
    expose:
      - "3000"
    networks:
      - webnet
    volumes:
      - sqlite-data:/app/data
  login_service:
    build: src/login_service/service/.
    container_name: login_service
    expose:
      - "3000"
    networks:
      - webnet
    volumes:
      - sqlite-data:/app/data
    environment:
      - JWT_SECRET=super_geheim
  game_service:
    build: src/game_service/service/.
    container_name: game_service
    expose:
      - "3000"
    networks:
      - webnet
    volumes:
      - sqlite-data:/app/data
  tournament_service:
    build: src/tournament_service/service/.
    container_name: tournament_service
    expose:
      - "3000"
    networks:
      - webnet
    volumes:
      - sqlite-data:/app/data
    depends_on:
      - database
  friends_service:
    build: src/friends_service/service/.
    container_name: friends_service
    expose:
      - "3000"
    networks:
      - webnet
    volumes:
      - sqlite-data:/app/data
    depends_on:
      - login_service
      - database
  profile_service:
    build: src/profile_service/service/.
    container_name: profile_service
    expose:
      - "3000"
    networks:
      - webnet
    volumes:
      - sqlite-data:/app/data
    environment:
      - JWT_SECRET=super_geheim

volumes:
  sqlite-data:
 
networks:
  webnet:
    